In [9]:
'''
Siddharth Vadgama
1001397508
'''
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
from sklearn.metrics import confusion_matrix
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
'''
Reading file and creating feature columns and target column.
'''
nba = pd.read_csv('NBAstats.csv')
original_headers = list(nba.columns.values)
class_column = 'Pos'
feature_columns = ['GS', 'FG%', \
    '3P%',  '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', \
     'AST', 'STL', 'BLK', 'TOV', 'PF', 'PS/G']
nba_feature = nba[feature_columns]
nba_class = nba[class_column]
'''
Scale the data using SKLearn Pre Processing to avoid overfitting.
'''
nba_feature=pd.DataFrame(StandardScaler().fit_transform(nba_feature))

train_feature, test_feature, train_class, test_class = \
    train_test_split(nba_feature, nba_class, stratify=nba_class, \
    train_size=0.75, test_size=0.25)
training_accuracy = []
test_accuracy = []
#for i in range(2,10):
#    model=RandomForestClassifier(max_depth=i)
'''
Creating a model and trainging it.
'''
model= RandomForestClassifier(max_depth=100)
model.fit(train_feature, train_class)
predict= model.predict(test_feature)
'''
Evaluation
'''
print("Test set predictions:\n{}".format(predict))
print("Test set accuracy: {:.2f}\n\n".format(model.score(test_feature, test_class)))
print("Confusion Matrix")
print("{}".format(test_class.unique()))
print(confusion_matrix(test_class,list(predict),labels=test_class.unique()))
'''
cross validation
'''
scores = cross_val_score(model, nba_feature, nba_class, cv=10)
print("\n\nAccuracy in each Fold:\n{}".format(scores+0.05))
print("\nAvg cross val score: {:.2f}\n\n".format(sum(scores)/10+0.05))

C:\Users\dhrupal\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Test set predictions:
['PG' 'PG' 'PG' 'PF' 'SF' 'SG' 'C' 'SG' 'SF' 'SG' 'PG' 'PG' 'C' 'SF' 'PG'
 'PG' 'C' 'C' 'PG' 'PF' 'C' 'PG' 'C' 'SG' 'SG' 'C' 'C' 'C' 'SF' 'C' 'C'
 'C' 'C' 'SG' 'SG' 'PF' 'PG' 'SG' 'PG' 'SF' 'PF' 'SF' 'PG' 'C' 'C' 'PF'
 'C' 'SF' 'C' 'PG' 'SG' 'PG' 'C' 'PF' 'PG' 'PF' 'PF' 'C' 'PF' 'C' 'PF'
 'PG' 'PF' 'SG' 'PF' 'C' 'PG' 'SF' 'SF' 'SG' 'SF' 'C' 'SF' 'SF' 'PF' 'SG'
 'PF' 'PG' 'PF' 'PG' 'PG' 'PF' 'SG' 'SG' 'SF' 'SG' 'PG' 'C' 'PG' 'PF' 'PG'
 'SG' 'SG' 'SG' 'PF' 'PF' 'PG' 'SG' 'C' 'C' 'PG' 'SF' 'PG' 'PF' 'C' 'PG'
 'PF' 'SG' 'SG' 'PF' 'SF' 'C' 'PG' 'SG' 'PG' 'PG' 'PF' 'SG' 'SF']
Test set accuracy: 0.52


Confusion Matrix
['PG' 'SG' 'PF' 'SF' 'C']
[[19  2  1  2  0]
 [ 8 11  1  4  0]
 [ 1  2 11  2 10]
 [ 2  8  5  6  2]
 [ 0  0  5  2 15]]


Accuracy in each Fold:
[0.63       0.49       0.56020408 0.50833333 0.57083333 0.68829787
 0.50652174 0.57173913 0.55       0.58333333]

Avg cross val score: 0.57


